In [ ]:
import pandas as pd
df=pd.read_csv(r'/content/WELFake_Dataset.csv',engine='python',error_bad_lines=False)

<ipython-input-57-77a98dc00683>:2: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  df=pd.read_csv(r'/content/WELFake_Dataset.csv',engine='python',error_bad_lines=False)
Skipping line 329: field larger than field limit (131072)
Skipping line 6464: field larger than field limit (131072)
Skipping line 70745: unexpected end of data
Skipping line 335: Expected 4 fields in line 335, saw 6
Skipping line 6463: Expected 4 fields in line 6463, saw 7
Skipping line 6464: Expected 4 fields in line 6464, saw 10
Skipping line 6466: Expected 4 fields in line 6466, saw 14
Skipping line 6468: Expected 4 fields in line 6468, saw 8
Skipping line 6469: Expected 4 fields in line 6469, saw 5
Skipping line 6470: Expected 4 fields in line 6470, saw 7
Skipping line 6471: Expected 4 fields in line 6471, saw 15
Skipping line 6472: Expected 4 fields in line 6472, saw 9
Skipping line 6473: Expected 4 fields in line 6473, sa

In [ ]:
df.head()

Unnamed: 0                                              title  \
0          0  LAW ENFORCEMENT ON HIGH ALERT Following Threat...   
1          1                                                NaN   
2          2  UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...   
3          3  Bobby Jindal, raised Hindu, uses story of Chri...   
4          4  SATAN 2: Russia unvelis an image of its terrif...   

                                                text label  
0  No comment is expected from Barack Obama Membe...     1  
1     Did they post their votes for Hillary already?     1  
2   Now, most of the demonstrators gathered last ...     1  
3  A dozen politically active pastors came here f...     0  
4  The RS-28 Sarmat missile, dubbed Satan 2, will...     1

In [ ]:
df.isnull().sum()

Unnamed: 0      0
title         554
text           57
label          20
dtype: int64

In [ ]:
df.shape

(70716, 4)

In [ ]:
df=df.dropna()

In [ ]:
df.head()

Unnamed: 0                                              title  \
0          0  LAW ENFORCEMENT ON HIGH ALERT Following Threat...   
2          2  UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...   
3          3  Bobby Jindal, raised Hindu, uses story of Chri...   
4          4  SATAN 2: Russia unvelis an image of its terrif...   
5          5  About Time! Christian Group Sues Amazon and SP...   

                                                text label  
0  No comment is expected from Barack Obama Membe...     1  
2   Now, most of the demonstrators gathered last ...     1  
3  A dozen politically active pastors came here f...     0  
4  The RS-28 Sarmat missile, dubbed Satan 2, will...     1  
5  All we can say on this one is it s about time ...     1

In [ ]:
# get the independent feature
x=df.drop('label',axis=1)

In [ ]:
y=df['label']

In [ ]:
# Checking if the dataset is balanced or not
y.value_counts()

1                                                  35776
0                                                  34332
 is just unbelievably rich from North Sea oil.         1
 за участие. Благодарю вас.                            1
Name: label, dtype: int64

In [ ]:
y.unique()

array(['1', '0', ' is just unbelievably rich from North Sea oil. ',
       ' за участие. Благодарю вас.'], dtype=object)

In [ ]:
y.replace(' is just unbelievably rich from North Sea oil. ','1', inplace=True)

In [ ]:
y.replace(' за участие. Благодарю вас.','1', inplace=True)

In [ ]:
y.value_counts()

1    35778
0    34332
Name: label, dtype: int64

In [ ]:
y=y.astype(int)

In [ ]:
import tensorflow as tf
from tensorflow.keras.layers import Embedding, LSTM, Bidirectional, Dense
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [ ]:
# Vocabulary_size
voc_size=5000

In [ ]:
message=x.copy()

In [ ]:
message.head()

Unnamed: 0                                              title  \
0          0  LAW ENFORCEMENT ON HIGH ALERT Following Threat...   
2          2  UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...   
3          3  Bobby Jindal, raised Hindu, uses story of Chri...   
4          4  SATAN 2: Russia unvelis an image of its terrif...   
5          5  About Time! Christian Group Sues Amazon and SP...   

                                                text  
0  No comment is expected from Barack Obama Membe...  
2   Now, most of the demonstrators gathered last ...  
3  A dozen politically active pastors came here f...  
4  The RS-28 Sarmat missile, dubbed Satan 2, will...  
5  All we can say on this one is it s about time ...

In [ ]:
message.reset_index(inplace=True)

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
import nltk
import re
from nltk.corpus import stopwords

In [ ]:
# Dataset Preprocessing
from nltk.stem import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(message['title'])):
    review = re.sub('[^a-zA-Z]', ' ', message['title'][i])
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)

In [ ]:
corpus

['law enforc high alert follow threat cop white blacklivesmatt fyf terrorist video',
 'unbeliev obama attorney gener say charlott rioter peac protest home state north carolina video',
 'bobbi jindal rais hindu use stori christian convers woo evangel potenti bid',
 'satan russia unv imag terrifi new supernuk western world take notic',
 'time christian group sue amazon splc design hate group',
 'dr ben carson target ir never audit spoke nation prayer breakfast',
 'hous intel chair trump russia fake stori evid anyth video',
 'sport bar owner ban nfl game show true american sport like speak rural america video',
 'latest pipelin leak underscor danger dakota access pipelin',
 'gop senat smack punchabl alt right nazi internet',
 'may brexit offer would hurt cost eu citizen eu parliament',
 'schumer call trump appoint offici overse puerto rico relief',
 'watch hilari ad call question health age clinton crime famili boss',
 'chang expect espn polit agenda despit huge subscrib declin breitbart'

In [ ]:
 onehot_rpr=[one_hot(words,voc_size) for words in corpus]

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [ ]:
onehot_rpr

[[1091, 4332, 2641, 3042, 62, 2917, 3503, 4679, 2847, 1621, 2417, 439],
 [2598,
  167,
  1747,
  853,
  3845,
  1561,
  4409,
  2621,
  2411,
  1421,
  2783,
  357,
  3120,
  439],
 [2423, 3531, 4384, 992, 4652, 1379, 3632, 1120, 4925, 763, 855, 2978],
 [4027, 3685, 4174, 2337, 3735, 3687, 1828, 3869, 1926, 3879, 4424],
 [4420, 3632, 2781, 1960, 3868, 722, 2165, 4083, 2781],
 [2904, 4359, 1760, 4728, 1302, 1392, 2188, 4345, 3776, 4400, 1344],
 [1389, 3343, 3540, 3535, 3685, 3008, 1379, 1907, 2393, 439],
 [1420,
  3657,
  787,
  1484,
  4094,
  4943,
  3700,
  3806,
  2025,
  1420,
  3913,
  2857,
  1606,
  1532,
  439],
 [636, 3034, 1897, 196, 2363, 4349, 1610, 3034],
 [3510, 2984, 118, 1437, 2652, 3109, 2942, 4166],
 [3533, 2922, 98, 1704, 1920, 957, 2283, 3044, 2283, 2542],
 [1518, 1710, 3535, 2681, 3265, 516, 1149, 3404, 2611],
 [724, 1448, 2303, 1710, 1997, 4005, 21, 3486, 2849, 1047, 2538],
 [1255, 4159, 1401, 4907, 155, 1663, 2551, 3859, 3752, 3407],
 [3258, 576, 1090, 4962, 1774

In [ ]:
# Embedding Representation

In [ ]:
sent_length = 20
embedded=pad_sequences(onehot_rpr, padding='pre',maxlen=sent_length)

In [ ]:
embedded

array([[   0,    0,    0, ..., 1621, 2417,  439],
       [   0,    0,    0, ...,  357, 3120,  439],
       [   0,    0,    0, ...,  763,  855, 2978],
       ...,
       [   0,    0,    0, ..., 1648, 2363,   29],
       [   0,    0,    0, ..., 2431, 2908,  439],
       [   0,    0,    0, ..., 3687,  260, 4420]], dtype=int32)

In [ ]:
# creating model
embedding_vector_features = 40
model = Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Bidirectional(LSTM(100)))
model.add(Dense(1, activation='sigmoid'))

In [ ]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 20, 40)            200000    
                                                                 
 bidirectional (Bidirection  (None, 200)               112800    
 al)                                                             
                                                                 
 dense_1 (Dense)             (None, 1)                 201       
                                                                 
Total params: 313001 (1.19 MB)
Trainable params: 313001 (1.19 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [ ]:
import numpy as np
x_final = np.array(embedded)
y_final = np.array(y)

In [ ]:
# train test split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_final,y_final,test_size=0.3,shuffle=y,random_state=10)

In [ ]:
early_stopping= tf.keras.callbacks.EarlyStopping(
    monitor="val_loss",
    min_delta=0.001,
    patience=20,
    verbose=0,
    mode="auto",
    baseline=None,
    restore_best_weights=False,
    start_from_epoch=0,
)

In [ ]:
# Model Training
model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=30, batch_size=32, callbacks=early_stopping)

Epoch 1/30
1534/1534 [==============================] - 17s 11ms/step - loss: 0.2356 - accuracy: 0.9026 - val_loss: 0.2509 - val_accuracy: 0.8945
Epoch 2/30
1534/1534 [==============================] - 14s 9ms/step - loss: 0.1929 - accuracy: 0.9229 - val_loss: 0.2502 - val_accuracy: 0.9009
Epoch 3/30
1534/1534 [==============================] - 18s 12ms/step - loss: 0.1594 - accuracy: 0.9367 - val_loss: 0.2480 - val_accuracy: 0.8996
Epoch 4/30
1534/1534 [==============================] - 15s 10ms/step - loss: 0.1290 - accuracy: 0.9499 - val_loss: 0.2743 - val_accuracy: 0.9010
Epoch 5/30
1534/1534 [==============================] - 14s 9ms/step - loss: 0.1041 - accuracy: 0.9593 - val_loss: 0.3107 - val_accuracy: 0.8967
Epoch 6/30
1534/1534 [==============================] - 14s 9ms/step - loss: 0.0838 - accuracy: 0.9673 - val_loss: 0.3607 - val_accuracy: 0.8869
Epoch 7/30
1534/1534 [==============================] - 15s 10ms/step - loss: 0.0648 - accuracy: 0.9754 - val_loss: 0.3777 - va

In [ ]:
y_pred = model.predict(x_test)

658/658 [==============================] - 3s 3ms/step


In [ ]:
y_pred = np.where(y_pred>0.5,1,0)

In [ ]:
y_pred

array([[1],
       [0],
       [1],
       ...,
       [1],
       [1],
       [0]])

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix
print('accuracy score of model is:',accuracy_score(y_test,y_pred))

accuracy score of model is: 0.8914562829838825


In [ ]:
print(confusion_matrix(y_test,y_pred))

[[8995 1246]
 [1037 9755]]
